### ISSUE TITLE
Implement Service Info

### ISSUE THREAD

**Issue by alex-hancock** [BD2KGenomics/consonance#4] opened 2017-10-07 00:04 UTC
Implement the [getServiceInfo()](https://github.com/BD2KGenomics/consonance/blob/feature/wes-support/consonance-webservice/src/main/java/io/swagger/wes/api/Ga4ghApiService.java) method in the Ga4ghApiService. 

Notes about Consonance implementation to follow. 

Notes about WES expectations of getServiceInfo() to follow.

**Comment by alex-hancock** [comment] 2017-10-09 19:15
Basing Consonance WES based on the back-end in [this](https://github.com/common-workflow-language/workflow-service/blob/master/wes_service/arvados_wes.py#L26) demo implementation.

**Comment by alex-hancock** [comment] 2017-11-06 20:36
Contacted Denis Yuen about proper implementations. Waiting to hear back to clarify proper format.

**Comment by kozbo** [comment] 2017-12-14 17:11
Duplicate of #12, closing

**Closed by kozbo** 2017-12-14 17:11 UTC
Labels: ready
